# This file was generated by GoReleaser. DO NOT EDIT.
cask "augur" do
  version "0.0.5-rc4"

  on_macos do
    on_intel do
      url "https://github.com/starkross/augur/releases/download/v#{version}/augur_#{version}_darwin_amd64.tar.gz"
      sha256 "29b5e6fcb75c5656ba71ee22fea5084fd47a192c2addf716c132c2b74d505109"
    end
    on_arm do
      url "https://github.com/starkross/augur/releases/download/v#{version}/augur_#{version}_darwin_arm64.tar.gz"
      sha256 "421152003501be98a642c5c0fe95225e6c698f96220111110a1e4fffffd91f30"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/starkross/augur/releases/download/v#{version}/augur_#{version}_linux_amd64.tar.gz"
      sha256 "c15969e036e883601788eb0816cb424efbe6830d8dcf474bfc57df914426a343"
    end
    on_arm do
      url "https://github.com/starkross/augur/releases/download/v#{version}/augur_#{version}_linux_arm64.tar.gz"
      sha256 "66e71363ca6be3c47dc0d4f2607bc56b7eb42406430df7f5edbb103811194abb"
    end
  end

  name "augur"
  desc "Policy-driven linter for OpenTelemetry configurations"
  homepage "https://github.com/starkross/augur"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "augur"

  # No zap stanza required

end
