# This file was generated by GoReleaser. DO NOT EDIT.
cask "augur" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/starkross/augur/releases/download/v#{version}/augur_#{version}_darwin_amd64.tar.gz"
      sha256 "c66f25895e82d7e21db00facd90d958fa771948a50056e36e2105c6098c3e071"
    end
    on_arm do
      url "https://github.com/starkross/augur/releases/download/v#{version}/augur_#{version}_darwin_arm64.tar.gz"
      sha256 "e894159fd520a685c93ec2350f0d16a9f7e7c725b3bb52a2cb23c5b61c32deb9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/starkross/augur/releases/download/v#{version}/augur_#{version}_linux_amd64.tar.gz"
      sha256 "3bfe1ce806f3b34746c579ed7c3b68abee4e33df37406bfacc55e4088826f4c9"
    end
    on_arm do
      url "https://github.com/starkross/augur/releases/download/v#{version}/augur_#{version}_linux_arm64.tar.gz"
      sha256 "84bfcde10a4887d9a8844d589f1a87cf32e8640c14ace4be78afd9887f6467cb"
    end
  end

  name "augur"
  desc "Policy-driven linter for OpenTelemetry configurations"
  homepage "https://github.com/starkross/augur"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "augur"

  # No zap stanza required

end
