# This file was generated by GoReleaser. DO NOT EDIT.
cask "augur" do
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/starkross/augur/releases/download/v#{version}/augur_#{version}_darwin_amd64.tar.gz"
      sha256 "ce2f7b3b36e4e58169a20427acddfc7ca484ebe42c54b9717181c9e16dbd0ac8"
    end
    on_arm do
      url "https://github.com/starkross/augur/releases/download/v#{version}/augur_#{version}_darwin_arm64.tar.gz"
      sha256 "d3eae8c1f11049f6728342f920c96f7ed7e6909da572819aa38d2d3bec5eafe3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/starkross/augur/releases/download/v#{version}/augur_#{version}_linux_amd64.tar.gz"
      sha256 "d00aacc3d222e50d98376aba13b3e6fa46b53687b4ec12c4cdf6697b8cd8f5af"
    end
    on_arm do
      url "https://github.com/starkross/augur/releases/download/v#{version}/augur_#{version}_linux_arm64.tar.gz"
      sha256 "d7607919610edbecf14b56088c096d6a47962c78f35bc7c76971d0c230d9f564"
    end
  end

  name "augur"
  desc "Policy-driven linter for OpenTelemetry configurations"
  homepage "https://github.com/starkross/augur"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "augur"

  # No zap stanza required

end
