# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Augur < Formula
  desc "Policy-driven linter for OpenTelemetry configurations"
  homepage "https://github.com/starkross/augur"
  version "0.0.5-rc"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/starkross/augur/releases/download/v0.0.5-rc/augur_0.0.5-rc_darwin_amd64.tar.gz"
      sha256 "dc678b735bfd66c25f7ce524abd46b28aa6f747e4c331bd9dae617e564c9521e"

      define_method(:install) do
        bin.install "augur"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/starkross/augur/releases/download/v0.0.5-rc/augur_0.0.5-rc_darwin_arm64.tar.gz"
      sha256 "580413aad0ca5eedc849e3f42bd3dabb8fd3c81c021720dbe3c411b91b693f75"

      define_method(:install) do
        bin.install "augur"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/starkross/augur/releases/download/v0.0.5-rc/augur_0.0.5-rc_linux_amd64.tar.gz"
      sha256 "2d995517df2c36bc564b5bb1f68fc935eb191fe516e8316993e211a98302f2fe"
      define_method(:install) do
        bin.install "augur"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/starkross/augur/releases/download/v0.0.5-rc/augur_0.0.5-rc_linux_arm64.tar.gz"
      sha256 "f8d77cb4f2cc16e5e81cb0798faba26aba647b97e54eae28d343e88938767f50"
      define_method(:install) do
        bin.install "augur"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/augur version")
  end
end
