# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Augur < Formula
  desc "Policy-driven linter for OpenTelemetry configurations"
  homepage "https://github.com/starkross/augur"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/starkross/augur/releases/download/v0.3.1/augur_0.3.1_darwin_amd64.tar.gz"
      sha256 "8aa90f20bd031c5d2332503a67d7fde97efff49f1396042e5c7cc9014ee482ac"

      define_method(:install) do
        bin.install "augur"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/starkross/augur/releases/download/v0.3.1/augur_0.3.1_darwin_arm64.tar.gz"
      sha256 "65bd7ac26f532d182438c9a469f7e0e9b8e447065da69200df1600435b008818"

      define_method(:install) do
        bin.install "augur"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/starkross/augur/releases/download/v0.3.1/augur_0.3.1_linux_amd64.tar.gz"
      sha256 "60ccef63760b1c65cb3eb8779b39d2a4a0877acba8a6449ebe26e1549b9466b1"
      define_method(:install) do
        bin.install "augur"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/starkross/augur/releases/download/v0.3.1/augur_0.3.1_linux_arm64.tar.gz"
      sha256 "9e859bcb5b109e51acf82dc73883764ab6f7ec75fe2c120456cff47934931de1"
      define_method(:install) do
        bin.install "augur"
      end
    end
  end

  test do
    system "#{bin}/augur", "--version"
  end
end
